UIEH-933: Add tags label assigned to Titles and Packages
folio-org/ui-eholdings pull request #1129
Opened 2020-08-27 10:22 UTC by Vladyslav-Velytskyi

## Description

Add tags label with assigned tags to Search Title and Search Package Accordions

## Issues
[UIEH-933](https://issues.folio.org/browse/UIEH-933)
[UIEH-934](https://issues.folio.org/browse/UIEH-934)

## Screenshots

![image](https://user-images.githubusercontent.com/55701515/91430884-37491280-e868-11ea-95a6-f2ea7c31a407.png)
![image](https://user-images.githubusercontent.com/55701515/91430951-52b41d80-e868-11ea-9151-f639b6ad0b6c.png)

2020-08-27 11:35 UTC, yelyzavetakhokhlova requested changes

2020-08-27 11:35 UTC, yelyzavetakhokhlova commented on src/components/search-package-list-item/search-package-list-item.js
> +import { isEmpty } from 'lodash';
please use default import from `lodash/isEmpty`

2020-08-27 16:01 UTC, yelyzavetakhokhlova approved these changes

2020-08-28 12:03 UTC, MaksymDryha approved these changes

2020-09-04 10:40 UTC, merged