UIEH-1105: Change displayed permission name for settings.eholdings.enabled
folio-org/ui-eholdings pull request #1290
Opened 2021-03-15 13:01 UTC by Vladyslav-Velytskyi

…abled

## Purpose

## Approach

#### TODOS and Open Questions

## Learning

## Screenshots

2021-03-15 13:41 UTC, Yuliia-Dovhal approved these changes

2021-03-16 09:50 UTC, BogdanDenis requested changes

2021-03-16 09:50 UTC, BogdanDenis commented on CHANGELOG.md
> +* Change displayed permission name for `module.eholdings.enabled`. (UIEH-1104)
Please remove duplicate line

2021-03-16 11:17 UTC, BogdanDenis approved these changes

2021-03-16 12:42 UTC, merged