UIEH-1043: Add tests coverage for keyboard shortcuts to eholdings
folio-org/ui-eholdings pull request #1296
Opened 2021-03-18 11:58 UTC by Yuliia-Dovhal

[UIEH-1043](https://issues.folio.org/browse/UIEH-1043)

## Purpose
Add tests coverage for keyboard shortcuts to eholdings

## Screenshots
![Screenshot 2021-03-18 at 13 51 48](https://user-images.githubusercontent.com/60929399/111622176-88632880-87f1-11eb-8d22-dfe5723eff7d.png)
![Screenshot 2021-03-18 at 13 52 35](https://user-images.githubusercontent.com/60929399/111622181-89945580-87f1-11eb-986f-a3231d5fc247.png)

2021-03-18 12:12 UTC, Vladyslav-Velytskyi approved these changes

2021-03-18 12:12 UTC, Vladyslav-Velytskyi commented on src/components/utililies.test.js
> +      preventDefault: jest.fn()
```suggestion
      dispatchEvent: jest.fn((event) => event),
    };
    const event = {
      preventDefault: jest.fn(),
```

2021-03-18 15:59 UTC, BogdanDenis requested changes

2021-03-18 15:59 UTC, BogdanDenis commented on src/components/package/create/package-create.js
> +              data-testid='data-test-eholdings-package-create'
Please use double quotes for attributes

2021-03-18 15:59 UTC, BogdanDenis commented on src/components/search-paneset/search-paneset.js
> +              data-testid='data-test-eholdings-search-pane'
Same here

2021-03-19 09:27 UTC, BogdanDenis approved these changes

2021-03-19 10:59 UTC, merged