UIEH-1052: Jest+RTL > Test PeerReviewedField, PublicationTypeField, PublisherNameField, TitleListItem and Toast
folio-org/ui-eholdings pull request #1361
Opened 2021-06-15 15:58 UTC by mariiaschv

## Purpose

- Refactoring
- Add tests for PeerReviewedField, PublicationTypeField, TitleListItem, Toast
- Tests for PublisherNameField have been already written

Issue: [UIEH-1052](https://issues.folio.org/browse/UIEH-1052)

2021-06-15 18:35 UTC, Vladyslav-Velytskyi requested changes

2021-06-15 18:35 UTC, Vladyslav-Velytskyi commented on src/components/title-list-item/title-list-item.test.js
> +      }
```suggestion
      },
```

2021-06-15 18:35 UTC, Vladyslav-Velytskyi commented on src/components/title-list-item/title-list-item.test.js
> +      }
```suggestion
      },
```

2021-06-15 18:35 UTC, Vladyslav-Velytskyi commented on src/components/title-list-item/title-list-item.test.js
> +          }
```suggestion
          },
```

2021-06-15 18:35 UTC, Vladyslav-Velytskyi commented on src/components/title-list-item/title-list-item.test.js
> +  describe('item metadata class', () => {
I'm not sure that you need this `describe`. Actually, describe should starts with word `when` and logically separate tests. I've recomended to add all props that you add to `testExtendedProps` in test set as default. In this case you don't need to set this data each time when you write test.

2021-06-15 18:35 UTC, Vladyslav-Velytskyi commented on src/components/title/_fields/publication-type/publication-type-field.js
>          <FormattedMessage id="ui-eholdings.filter.pubType.audioBook">
Could you also fix this duplication like it done for `PackageContentTypeField`?

2021-06-15 18:35 UTC, Vladyslav-Velytskyi commented on src/components/title/_fields/publication-type/publication-type-field.test.js
> +  it('should display Audiobook option', () => {
Just suggestion. You could write this tests in cycle.
For example
```
Object.values(objOfTypes).forEach(value => {
  it('should display option', () => {
     const { getByText } = renderPublicationTypeField();
   
     expect(getByText(`ui-eholdings.filter.pubType.${value}`)).toBeDefined();  
  });
});
```
or
```
it('should display options', () => {
  const { getByText } = renderPublicationTypeField();
   
  Object.values(objOfTypes).forEach(value => {
    expect(getByText(`ui-eholdings.filter.pubType.${value}`)).toBeDefined(); 
  });
});
```

2021-06-16 10:34 UTC, Vladyslav-Velytskyi approved these changes
LGTM!

2021-06-16 11:38 UTC, BogdanDenis requested changes

2021-06-16 11:38 UTC, BogdanDenis commented on src/components/title-list-item/title-list-item.test.js
> +    <Router history={routerHistory}>
You can use `<Harness>` component from `test/jest/helpers/harness`. It already has a router and other mocked components

2021-06-22 09:07 UTC, BogdanDenis approved these changes

2021-06-22 09:21 UTC, merged