UIEH-1159: View Package Record : Updates to Package Settings display
folio-org/ui-eholdings pull request #1401
Opened 2021-08-03 12:12 UTC by mariiaschv

## Purpose
Change Package Settings display on View Package details record

## Screenshots
![image](https://user-images.githubusercontent.com/84023879/128013167-23b02a1e-f93a-41de-b40b-6be7ec8306f9.png)
===
![image](https://user-images.githubusercontent.com/84023879/128013185-cbb5635c-7002-485a-81f7-d531c2ae56f7.png)

## Issues
[UIEH-1159](https://issues.folio.org/browse/UIEH-1159)

2021-08-03 12:33 UTC, Vladyslav-Velytskyi commented on src/components/package/show/components/package-settings/package-settings.js
> +                            : <FormattedMessage id="ui-eholdings.no" />
Please, move it in separate variable

2021-08-03 14:33 UTC, BogdanDenis requested changes

2021-08-03 14:33 UTC, BogdanDenis commented on src/components/package/show/components/package-settings/package-settings.js
> +                      : <FormattedMessage
Please format this like so:
```
? <FormattedMessage id="ui-eholdings.yes" />
: (
    <FormattedMessage
        id="ui-eholdings.package.visibility.no"
        values={{ visibilityMessage }}
    />
)
```

2021-08-04 10:02 UTC, Vladyslav-Velytskyi approved these changes

2021-08-05 09:57 UTC, BogdanDenis approved these changes

2021-08-05 10:41 UTC, merged