UIEH-1077: Jest+RTL > Test SettingsCustomLabels
folio-org/ui-eholdings pull request #1420
Opened 2021-08-18 14:41 UTC by mariiaschv

## Purpose

- Add tests for SettingsCustomLabels component
- Refactoring

Issue: [UIEH-1077](https://issues.folio.org/browse/UIEH-1077)

2021-08-19 06:31 UTC, Vladyslav-Velytskyi approved these changes

2021-08-20 08:22 UTC, BogdanDenis requested changes

2021-08-20 08:22 UTC, BogdanDenis commented on src/components/settings/settings-custom-labels/settings-custom-labels.js
> +  }, [customLabels]);
You should pass `customLabels.isUpdated` as a dependency. Passing just `customLabels` will cause the callback to be called too many times when a reference to `customLabels` has changed, but `isUpdated` value is still the same

2021-08-20 08:45 UTC, BogdanDenis approved these changes

2021-08-20 08:46 UTC, merged