UIEH-1092: Add tests for CustomEditPackage component
folio-org/ui-eholdings pull request #1437
Opened 2021-09-13 11:07 UTC by Vladyslav-Velytskyi

## Purpose

## Approach

#### TODOS and Open Questions

## Learning

## Screenshots

2021-09-13 12:23 UTC, mariiaschv requested changes

2021-09-13 12:23 UTC, mariiaschv commented on src/components/package/edit-custom/custom-package-edit.test.js
> +
I believe one empty line will be enough here

2021-09-13 12:23 UTC, mariiaschv commented on src/components/package/edit-custom/custom-package-edit.test.js
> +      screen.debug();
Please remove this line

2021-09-13 12:58 UTC, mariiaschv approved these changes

2021-09-14 10:09 UTC, BogdanDenis approved these changes

2021-09-14 11:15 UTC, merged