UIEH-1185: Add tests for NoteCreate, NoteEdit, NoteView Routes
folio-org/ui-eholdings pull request #1482
Opened 2021-12-16 13:39 UTC by Svitlana-Korol

https://issues.folio.org/browse/UIEH-1185

2021-12-16 13:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/folio-org/ui-eholdings?pullRequest=1482) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/folio-org/ui-eholdings?pullRequest=1482) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/folio-org/ui-eholdings?pullRequest=1482) it.</sub>

2021-12-16 15:55 UTC, Vladyslav-Velytskyi requested changes
Please, also fix lint issues, related to your changes

2021-12-16 15:55 UTC, Vladyslav-Velytskyi commented on CHANGELOG.md
> +
Please, remove this unnecessary empty string

2021-12-16 15:55 UTC, Vladyslav-Velytskyi commented on src/routes/note-edit.test.js
> +import { render, cleanup, act, fireEvent } from '@testing-library/react';
When we destructuring more then one element from the file, we write each variable on separate string, please, refactor it.

```suggestion
import {
  render,
  cleanup,
  act,
  fireEvent,
} from '@testing-library/react';
```

2021-12-16 15:55 UTC, Vladyslav-Velytskyi commented on src/routes/note-create.test.js
> +  goBack: jest.fn()
Don't forget about commas after each value in object
```suggestion
  goBack: jest.fn(),
```

2021-12-16 15:55 UTC, Vladyslav-Velytskyi commented on src/routes/note-create.test.js
> +  });
What are you testing here? It should be `expect` construction inside `it`'s callback

2021-12-16 15:55 UTC, Vladyslav-Velytskyi commented on src/routes/note-edit.test.js
> +    });
This is not a test too

2021-12-16 15:55 UTC, Vladyslav-Velytskyi commented on src/routes/note-view.test.js
> +  });
Rewrite it please too

2021-12-16 15:55 UTC, Vladyslav-Velytskyi commented on src/routes/note-edit.test.js
> +        it('should navigateBack', () => {
Suggestion to rename
```suggestion
    describe('when click on navigate back button', () => {
        it('should handle "history.goBack"', () => {
```

2021-12-16 16:18 UTC, mariiaschv requested changes

2021-12-16 16:18 UTC, mariiaschv commented on src/routes/note-create.test.js
> +import { render, cleanup, act } from '@testing-library/react';
Please, refactor this also to have variables on separate lines.

2021-12-16 16:18 UTC, mariiaschv commented on src/routes/note-edit.test.js
> +        }) => (
I think, you can leave it on one line here as you have only one variable here.
```suggestion
        ({ navigateBack }) => (
```

2021-12-16 16:18 UTC, mariiaschv commented on src/routes/note-view.test.js
> +import { render, cleanup, act, fireEvent } from '@testing-library/react';
This also should be on separate lines.

2021-12-16 16:18 UTC, mariiaschv commented on src/routes/note-view.test.js
> +    it('should navigate back', () => {
You test here a case when you don't have `location.state`, so I suggest to rename the test case:
```suggestion
    it('should redirect to eholdings page', () => {
```

But you also have a case with `location.state` present and there it should handle "history.goBack" and you can add a test for it too.

2021-12-16 16:20 UTC, mariiaschv reviewed
And you also should sigh the required Contributor License Agreement to have the checks passed.

2021-12-17 08:54 UTC, BogdanDenis requested changes

2021-12-17 08:54 UTC, BogdanDenis commented on src/routes/note-edit.test.js
> +            <>
We can simply return `<button>` without `<>` because it's a single element

2021-12-17 14:48 UTC, BogdanDenis approved these changes

2021-12-17 16:23 UTC, mariiaschv approved these changes

2021-12-17 16:50 UTC, Vladyslav-Velytskyi approved these changes

2021-12-17 16:57 UTC, merged