UIEH-1188: Jest+RTL > Test PackageShowRoute
folio-org/ui-eholdings pull request #1502
Opened 2022-02-14 16:43 UTC by mariiaschv

## Purpose
Add tests for `PackageShowRoute` component.

## Screenshots

### Component code coverage
![image](https://user-images.githubusercontent.com/84023879/153909466-c647518c-03fb-4ef2-94c6-c47c1c2e1d3b.png)

## Issues
[UIEH-1188](https://issues.folio.org/browse/UIEH-1188)

2022-02-15 14:50 UTC, Svitlana-Korol approved these changes

2022-02-16 12:30 UTC, BogdanDenis requested changes

2022-02-16 12:30 UTC, BogdanDenis commented on src/routes/package-show-route/package-show-route.test.js
> +    expect(mockGetPackage).toHaveBeenCalled();
Please check that this function is called with correct id

2022-02-16 12:30 UTC, BogdanDenis commented on src/routes/package-show-route/package-show-route.test.js
> +    expect(mockGetProvider).toHaveBeenCalled();
Please check that this function is called with correct id

2022-02-16 12:30 UTC, BogdanDenis commented on src/routes/package-show-route/package-show-route.test.js
> +      expect(mockGetPackage).toHaveBeenCalled();
Please check that the function is called with new id

2022-02-16 12:30 UTC, BogdanDenis commented on src/routes/package-show-route/package-show-route.test.js
> +      expect(mockGetPackageTitles).toHaveBeenCalled();
Please check that this is called with correct search params

2022-02-17 10:03 UTC, BogdanDenis approved these changes

2022-02-17 10:06 UTC, merged