UIEH-1265: Replace or remove react-hot-loader
folio-org/ui-eholdings pull request #1529
Opened 2022-04-04 13:33 UTC by Svitlana-Korol

## Description
Remove react-hot-loader

## Issues
[UIEH-1265](https://issues.folio.org/browse/UIEH-1265)

2022-04-04 15:28 UTC, BogdanDenis requested changes

2022-04-04 15:28 UTC, BogdanDenis commented on package.json
> -    "react-hot-loader": "^4.3.12",
This dep is used in `src/index`, so we should also remove it's use there

2022-04-05 08:46 UTC, BogdanDenis approved these changes

2022-04-05 09:58 UTC, mariiaschv approved these changes

2022-04-05 09:59 UTC, merged