UIEH-1259: Package Detail Record> Usage & analysis accordion > Apply pagination to Titles list
folio-org/ui-eholdings pull request #1534
Opened 2022-04-11 15:59 UTC by mariiaschv

## Purpose
Apply pagination to Titles list in Usage & analysis accordion on Package Detail Record.

#### TODOS and Open Questions
Discuss if we need to show loading view between clicking prev/next button and having new page results loaded. Right now there's old results displayed while the request is being processed.

## Screenshots
https://user-images.githubusercontent.com/84023879/162781719-5fc9e78f-f233-4529-be3c-3813026f5d21.mp4

## Issues
[UIEH-1259](https://issues.folio.org/browse/UIEH-1259)

Related PRs: [](url)

2022-04-13 11:46 UTC, BogdanDenis requested changes

2022-04-13 11:46 UTC, BogdanDenis commented on src/features/usage-consolidation-accordion/titles-table/titles-table.test.js
> +          expect(mockFetchPage).toHaveBeenCalled();
Please also check that `mockFetchPage` is called with correct page number

2022-04-15 08:34 UTC, Svitlana-Korol approved these changes

2022-04-15 08:36 UTC, BogdanDenis approved these changes

2022-04-15 11:24 UTC, ODanyor approved these changes

2022-04-15 19:00 UTC, merged